networks:
  earth_orbit_network:
    ipam:
      config:
      - subnet: 172.26.0.0/16
  earth_surface_network:
    ipam:
      config:
      - subnet: 172.25.0.0/16
  moon_orbit_network:
    ipam:
      config:
      - subnet: 172.28.0.0/16
  moon_surface_network:
    ipam:
      config:
      - subnet: 172.27.0.0/16
services:
  earth_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_orbit_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.26.1.2
    ports:
    - 50001:5001
    privileged: true
    tty: true
  earth_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_surface_1
    networks:
      earth_surface_network:
        ipv4_address: 172.25.1.2
    ports:
    - 50000:5001
    privileged: true
    tty: true
  moon_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_orbit_1
    networks:
      moon_orbit_network:
        ipv4_address: 172.28.1.2
    ports:
    - 50002:5001
    privileged: true
    tty: true
  moon_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_1
    networks:
      moon_surface_network:
        ipv4_address: 172.27.1.2
    ports:
    - 50003:5001
    privileged: true
    tty: true
  relay_earth_orbit_moon_orbit:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_orbit_moon_orbit
    networks:
      earth_orbit_network:
        ipv4_address: 172.26.0.3
      moon_orbit_network:
        ipv4_address: 172.28.0.3
    ports:
    - 50007:5001
    privileged: true
    tty: true
  relay_earth_orbit_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_orbit_moon_surface
    networks:
      earth_orbit_network:
        ipv4_address: 172.26.0.4
      moon_surface_network:
        ipv4_address: 172.27.0.3
    ports:
    - 50008:5001
    privileged: true
    tty: true
  relay_earth_surface_earth_orbit:
    image: vyos/vyos-build:sagitta-arm64
    platform: linux/arm64/v8
    build:
      context: ./
      dockerfile: ./input/Dockerfile1
    container_name: relay_earth_surface_earth_orbit
    networks:
      earth_orbit_network:
        ipv4_address: 172.26.0.2
      earth_surface_network:
        ipv4_address: 172.25.0.2
    ports:
    - 50004:5001
    privileged: true
    tty: true
  relay_earth_surface_moon_orbit:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_surface_moon_orbit
    networks:
      earth_surface_network:
        ipv4_address: 172.25.0.3
      moon_orbit_network:
        ipv4_address: 172.28.0.2
    ports:
    - 50005:5001
    privileged: true
    tty: true
  relay_earth_surface_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_surface_moon_surface
    networks:
      earth_surface_network:
        ipv4_address: 172.25.0.4
      moon_surface_network:
        ipv4_address: 172.27.0.2
    ports:
    - 50006:5001
    privileged: true
    tty: true
  relay_moon_orbit_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_moon_orbit_moon_surface
    networks:
      moon_orbit_network:
        ipv4_address: 172.28.0.4
      moon_surface_network:
        ipv4_address: 172.27.0.4
    ports:
    - 50009:5001
    privileged: true
    tty: true
version: '3'
